[project]
name = "worker-vllm"
version = "0.9.2-rc.1"
description = "The RunPod worker template for serving our large language model endpoints. Powered by vLLM."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "vllm>=0.9.2",
]
